name: Check URL

on:
  push:
    branches:
      - main
  # in a real app the below would be enabled
  # disabled as this is just a test repo
  # triggered by push to main branch only now

  # schedule:
  #   - cron: '0 * * * *' # runs every hour, on the hour

jobs:
  ping_url:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://hairy-mushroom-soup.fly.dev/
