name: Check URL

on:
  # push is just for testing
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 * * * *' # runs every hour, on the hour

jobs:
  ping_url:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://hairy-mushroom-soup.fly.dev/
